SG-123 fix quantity and logo
retail-red/shopware-6 pull request #6
Opened 2022-11-08 11:54 UTC by augsteyer

### Changed logo:
![image](https://user-images.githubusercontent.com/844601/200557130-290478aa-77ed-403b-8cbb-a67f2a841cc3.png)

### Fixed issue with string -> int:

![image](https://user-images.githubusercontent.com/844601/200557285-a66255f2-388d-491d-84b4-862e8b8c4991.png)

2022-11-08 11:55 UTC, augsteyer commented
@Rekhyt I cannot assign you on this one, so you are it! :)

2022-11-15 12:38 UTC, Rekhyt requested changes

2022-11-15 12:38 UTC, Rekhyt commented on CHANGELOG.md
> +- to new Shopgate logo
```suggestion
- replaced retail.red logo with the new one from Shopgate
```

2022-11-15 12:38 UTC, Rekhyt commented on CHANGELOG.md
> +- product quantity change was providing data as a string instead of the required integer
```suggestion
- product quantity sent as a string to the API, number required
```

2022-11-15 15:48 UTC, augsteyer commented
Apparently I cannot batch commit for some reason :/

2022-11-15 15:48 UTC, Rekhyt approved these changes

2022-11-15 15:49 UTC, merged

2022-11-15 15:50 UTC, Rekhyt commented
> Apparently I cannot batch commit for some reason :/

np, merged, thank you for the PR :+1: