SG-123 fix properties
retail-red/shopware-6 pull request #7
Opened 2022-11-28 07:52 UTC by augsteyer

Changes as they are hard to see.

Quotes added, json_encode removed:
```
                  legal: {
                    terms: '{{ config('SgateClickAndReserveSW6.config.termsLink') |default(null) }}',
                    privacy: '{{ config('SgateClickAndReserveSW6.config.privacyLink') |default(null) }}',
```
Fallback added when EAN is absent (not a required field):
```
 product: {
                    code: '{% if productCodeMapping == 'ean' and page.product.ean is defined %}{{ page.product.ean }}{% else %}{{ page.product.productNumber }}{% endif %}',
```

Added fix for single product child products by early returning data if sorted properties did not have the variant info:
```
options: variants.map(function (variant) {
                      if (!product.sortedProperties) {
                        return getBasicVariantData(variant);
                      }
                      const sortedProperty = product.sortedProperties.find(function(sortedProperty) {
                        return sortedProperty.name === variant.group
                      })
                      if (!(sortedProperty && sortedProperty.options)) {
                        return getBasicVariantData(variant);
                      }
```

2022-11-28 07:52 UTC, augsteyer commented
@Rekhyt all yours!

2023-04-03 14:39 UTC, Rekhyt requested changes
Sorry for the wait.

I only found some wording issues, mostly stuff that was already there. I could not apply them myself as the source is your repo but I guess suggestions work fine, too :-)

Thank you for the PR.

2023-04-03 14:39 UTC, Rekhyt commented on src/Resources/config/config.xml
> +            <helpText lang="de-DE">Sobald aktiviert, kann der Nutzer die Browser Historie zur Navigation im Reservierungs-Prozess nutzen.</helpText>
```suggestion
            <helpText lang="de-DE">Erlaubt Nutzern die Benutzung der Browser-Historie zur Navigation im Reservierungs-Prozess. Deaktivieren Sie diese Funktion, falls ihr Theme bereits eine solche Navigation anbietet und dadurch ein Konflikt mit der Plugin-Funktionalität entsteht.</helpText>
```

2023-04-03 14:39 UTC, Rekhyt commented on src/Resources/config/config.xml
> +            <helpText lang="de-DE">Wenn diese Option aktiviert wird, wird der Zugriff auf die Geo Location sofort nach öffnen der Filial-Übersicht angefragt.</helpText>
```suggestion
            <helpText>If enabled, whenever the user opens the store list the browser's geolocation will be requested immediately instead of only after pressing the "locate me" button.</helpText>
            <helpText lang="de-DE">Wenn diese Option aktiviert ist, wird der Zugriff auf die Geo-Location sofort nach dem Öffnen der Filial-Übersicht angefragt.</helpText>
```

2023-04-03 14:39 UTC, Rekhyt commented on src/Resources/config/config.xml
> +                When set to true no buttons will be rendered within the users' browser, till the page was once opened with a query parameter like rrTesting=start. A testing session can be stopped by
```suggestion
                When set to true no buttons will be rendered within the users' browser, until the page was once opened with query parameter "rrTesting=start". The testing session can be terminated by opening the page with "rrTesting=end".
```

2023-04-03 14:39 UTC, Rekhyt commented on src/Resources/config/config.xml
> +            <helpText lang="de-DE">Wenn diese Option aktiviert wird, werden keine Buttons auf der Produktdetailseite angezeigt. Um die Buttons anzuzeigen, muss der Parameter "rrTesting=Start" an die
```suggestion
            <helpText lang="de-DE">Wenn diese Option aktiviert wird, werden keine Buttons auf der Produktdetailseite angezeigt. Um die Buttons anzuzeigen, muss der Parameter "rrTesting=start" an die URL angehängt werden. Die Test-Session kann durch den Parameter "rrTesting=end" gestoppt werden.</helpText>
```

2023-04-03 14:39 UTC, Rekhyt commented on src/Resources/config/config.xml
> +            <helpText lang="de-DE">Wählen Sie welche Version der Reservierung genutzt werden soll: Reservation Button = "Reservieren" Button, welcher die Filialsuche öffnet. Availability in Store = E
```suggestion
            <helpText lang="de-DE">Wählen Sie, welche Version der Reservierung genutzt werden soll: "Reservation Button": Es wird ein Button mit der Aufschrift "Reservieren" angezeigt, welcher die Filialsuche öffnet. "Availability in Store": Der Nutzer wählt eine Filiale und es wird immer der lokale Bestand dieser Filiale angezeigt.</helpText>
```

2023-04-03 14:39 UTC, Rekhyt commented on src/Resources/config/config.xml
> +            <helpText lang="de-DE">Wenn der Beständ niedriger als angegeben ist, wird "X Verfügbar" in der state-warning Farbe angezeigt.</helpText>
```suggestion
            <helpText lang="de-DE">Wenn der Bestand niedriger als angegeben ist, wird "X Verfügbar" in der state-warning Farbe angezeigt.</helpText>
```

2023-04-03 14:39 UTC, Rekhyt commented on src/Resources/config/config.xml
> +            <helpText lang="de-DE">Wenn der Beständ höher als angegeben ist, wird "X+ Verfügbar" angezeigt.</helpText>
```suggestion
            <helpText lang="de-DE">Wenn der Bestand höher als angegeben ist, wird "X+ Verfügbar" angezeigt.</helpText>
```

2023-04-04 16:21 UTC, Rekhyt approved these changes

2023-04-04 16:21 UTC, merged